Scripts/Daily/Daily/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'Dailyapp/',include('Dailyapp.urls')),
]

Scripts/Daily/Dailyapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from Dailyapp import views

app_name = 'Dailyapp'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

#   url(r'^detail/', views.detail, name = 'detail' ),
#   url(r'^admin/', admin.site.urls),
]

Scripts/Daily/Dailyapp/models.py
from django.db import models

# Create your models here.


class Task(models.Model):

    def __str__(self):
        return self.task_name

    task_name = models.CharField(max_length = 200)
    task_priority = models.CharField(max_length= 200)

Scripts/Daily/Dailyapp/views.py
from django.views import generic
from .models import Task

class IndexView(generic.ListView):
    template_name = 'Dailyapp/index.html'

    def get_queryset(self):
        return Task.objects.all()

class DetailView(generic.DetailView):
    model = Task
    template_name = 'Dailyapp/detail.html'

Scripts/Daily/Dailyapp/templates/Dailyapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href = "{% static 'Dailyapp/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>


<nav class="navbar navbar-inverse">
                <div class="container-fluid">
                   <div class="navbar-header">
                       <a class="navbar-brand" href="#">Todoapp</a>
                   </div>
                    <ul class="nav navbar-nav">
                        <li class="active"> <a href="#">Item 1</a></li>
                        <li><a href="#">Item 2</a></li>
                         <li><a href="#">Item 3</a></li>
                         <li><a href="#">Item 4</a></li>
                         <li><a href="#">Item 5</a></li>
                         <li><a href="#">Item 6</a></li>
                         <li><a href="#">Item 7</a></li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"> <a href="#">Item 1</a></li>
                        <li><a href="#">Item 2</a></li>
                         <li><a href="#">Item 3</a></li>
                         <li><a href="#">Item 4</a></li>
                         <li><a href="#">Item 5</a></li>
                         <li><a href="#">Item 6</a></li>
                         <li><a href="#">Item 7</a></li>
                    </ul>
                </div>
            </nav>

        {% block body %}

        {% endblock %}


</body>
</html>

Scripts/Daily/Dailyapp/templates/Dailyapp/detail.html
{% extends 'Dailyapp/base.html' %}
<!DOCTYPE html>

 {% block body %}
{{task.task_name}} </br>
{{task.task_priority}}

{% endblock %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Scripts/Daily/Dailyapp/templates/Dailyapp/index.html
{% extends 'Dailyapp/base.html' %}
<!DOCTYPE html>


<html>
<head>


    <meta charset="UTF-8">
    <title>DAILY APP</title>
</head>
<body>

        {% block body %}

                <div class="container">
                    <h2> <strong><center>TODAY'S LIST</center></strong></h2>
                    <marquee> <h3><strong> GET SHIT DONE.</strong> </h3></marquee>
                    <table class="table">
                        <thead>
                            <tr>
                            <th>Task Name</th>
                            <th>Task Priority</th>
                            <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                {% if task_list %}
                 {% for task in object_list %}
                <tr class="active">
                    <td><a href="{% url 'Dailyapp:detail' task.id %}">{{task.task_name}}</a></td>
                    <td><b>{{task.task_priority}}</b></td>
                    <td><button type="submit" class="btn btn-success"> DONE</button></td>
                </tr>
                {% endfor %}

                {% endif %}
                </tbody>
            </table>
        </div>
{% endblock %}




</body>
</html>